
import './globals.css'
import type { Metadata } from 'next'
import {  Saira_Stencil_One } from 'next/font/google'

const saira = Saira_Stencil_One({ weight: "400",preload:false })

export const metadata: Metadata = {
  title: 'Glowing Phoenix Banda de Metal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={saira.className + " w-screen h-screen"}>
        {children}

        </body>
    </html>
  )
}
